# Generated by Django 5.2.12 on 2026-04-17 02:25

import django.core.validators
import django.db.models.deletion
import repository.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('color', models.CharField(default='#465C78', max_length=7, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('function', models.CharField(blank=True, max_length=140, verbose_name='função')),
                ('institutional_link', models.CharField(blank=True, max_length=180, verbose_name='vínculo institucional')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_person', to=settings.AUTH_USER_MODEL, verbose_name='usuário vinculado')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descrição')),
                ('cover_image', models.ImageField(blank=True, upload_to=repository.models.project_cover_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='imagem de capa')),
                ('location', models.CharField(blank=True, max_length=220, verbose_name='localização/unidade')),
                ('requested_by', models.CharField(blank=True, max_length=220, verbose_name='demandante')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='in_progress', max_length=30, verbose_name='status')),
                ('visibility', models.CharField(choices=[('public', 'Catálogo público'), ('restricted', 'Restrito')], default='public', max_length=30, verbose_name='visibilidade')),
                ('notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='repository.category', verbose_name='categorias')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordination', 'Coordenação'), ('architecture', 'Arquitetura'), ('engineering', 'Engenharia'), ('intern', 'Estágio/Bolsista'), ('collaborator', 'Colaboração'), ('other', 'Outro')], default='collaborator', max_length=40, verbose_name='papel')),
                ('responsibility', models.CharField(blank=True, max_length=180, verbose_name='responsabilidade')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='repository.person', verbose_name='pessoa')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='repository.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'integrante do projeto',
                'verbose_name_plural': 'integrantes do projeto',
                'ordering': ['order', 'person__name'],
                'unique_together': {('project', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='projects', through='repository.ProjectMember', to='repository.person', verbose_name='equipe'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team', 'Equipe'), ('reader', 'Leitor')], default='reader', max_length=20, verbose_name='perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuário',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('file', models.FileField(storage=repository.models.PrivateMediaStorage(), upload_to=repository.models.project_file_upload_path, validators=[repository.models.validate_project_file_extension, repository.models.validate_upload_size], verbose_name='arquivo')),
                ('file_type', models.CharField(choices=[('dwg', 'DWG/AutoCAD'), ('dxf', 'DXF'), ('pdf', 'PDF'), ('image', 'Imagem/render'), ('model_3d', 'Modelo 3D'), ('spreadsheet', 'Planilha'), ('memorial', 'Memorial/descritivo'), ('other', 'Outro')], max_length=40, verbose_name='tipo')),
                ('discipline', models.CharField(choices=[('architecture', 'Arquitetônico'), ('electrical', 'Elétrico'), ('hydraulic', 'Hidrossanitário'), ('logic', 'Lógica/rede'), ('landscape', 'Paisagismo'), ('urbanism', 'Urbanismo'), ('accessibility', 'Acessibilidade'), ('hvac', 'Climatização'), ('fire', 'Prevenção e combate a incêndio'), ('signage', 'Comunicação visual/sinalização'), ('compatibility', 'Compatibilização'), ('other', 'Outro')], default='architecture', max_length=40, verbose_name='disciplina')),
                ('version', models.CharField(default='v1', max_length=40, verbose_name='versão')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('current', 'Atual'), ('superseded', 'Substituído'), ('draft', 'Rascunho')], default='current', max_length=40, verbose_name='status')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repository.project', verbose_name='projeto')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_files', to='repository.person', verbose_name='responsável técnico')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'arquivo do projeto',
                'verbose_name_plural': 'arquivos do projeto',
                'ordering': ['-uploaded_at', 'title'],
                'indexes': [models.Index(fields=['project', 'file_type'], name='repository__project_bc60ec_idx'), models.Index(fields=['project', 'discipline'], name='repository__project_0a9907_idx'), models.Index(fields=['status'], name='repository__status_a5867d_idx')],
            },
        ),
    ]
